apiVersion: batch/v1
kind: CronJob
metadata:
  name: backups
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          nodeName: supermicro1
          restartPolicy: Never
          serviceAccountName: backups
          volumes:
            - name: script
              configMap:
                name: backup-script
            - name: config
              configMap:
                name: rclone-config-backups
          containers:
            - name: backups
              image: ghcr.io/thelab-ms/backupenv:main-e1087cd
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: script
                  mountPath: /bin/backup.py
                  subPath: backup.py
                - name: config
                  mountPath: /config/rclone/rclone.conf
                  subPath: rclone.conf
              command:
                - /usr/bin/python3
                - /bin/backup.py
              env:
                - name: AZURE_TENANT_ID
                  value: f4ba79ec-fe30-424f-a96e-2de98f58f9b8 # life is short, hardcode
                - name: AZURE_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: azure-sp
                      key: clientID
                - name: AZURE_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: azure-sp
                      key: secret

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config-backups
data:
  rclone.conf: |
    [sqlbackups]
    type = azureblob
    account = thelabbackupssql
    env_auth = true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backups

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backups
subjects:
  - kind: ServiceAccount
    name: backups
    namespace: default
roleRef:
  kind: ClusterRole
  name: admin # yolo
  apiGroup: rbac.authorization.k8s.io
