apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cto@thelab.ms
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: cto@thelab.ms
            apiKeySecretRef:
              name: cloudflare-auth
              key: token

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace: default
spec:
  secretName: wildcard-cert
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io
  commonName: "*.thelab.ms"
  dnsNames:
    - "*.thelab.ms"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-wildcard
  namespace: default
spec:
  secretName: apps-wildcard-cert
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io
  commonName: "*.apps.thelab.ms"
  dnsNames:
    - "*.apps.thelab.ms"

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: internal-ca
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-ca
spec:
  isCA: true
  commonName: thelab-internal-ca
  secretName: internal-ca
  duration: 927100h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: internal-ca
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: internal
spec:
  ca:
    secretName: internal-ca
