apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: projectcontour
spec:
  $patch: replace
  type: ClusterIP
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: 8080
  - port: 443
    name: https
    protocol: TCP
    targetPort: 8443
