apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: projectcontour
spec:
  $patch: replace
  type: LoadBalancer
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 8080
  - port: 8443
    name: https
    protocol: TCP
    targetPort: 8443
