apiVersion: apps/v1
kind: Deployment
metadata:
  name: anything
spec:
  template:
    spec:
      containers:
      - name: oauth2proxy
        image: oauth2-proxy
        volumeMounts:
          - name: proxy-keycloak-creds
            mountPath: /var/lib/keycloak
        env:
        - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
          value: "true"
        - name: OAUTH2_PROXY_SILENCE_PING_LOGGING
          value: "true"
        - name: OAUTH2_PROXY_SCOPE
          value: "openid email profile"
        - name: OAUTH2_PROXY_HTTP_ADDRESS
          value: ":8880"
        - name: OAUTH2_PROXY_EMAIL_DOMAINS
          value: "*"
        - name: OAUTH2_PROXY_CLIENT_ID
          value: "oauthproxy"
        - name: OAUTH2_PROXY_PROVIDER
          value: "keycloak-oidc"
        - name: OAUTH2_PROXY_PASS_USER_HEADERS
          value: "true"
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          value: "https://keycloak.apps.thelab.ms/realms/master"
        - name: OAUTH2_PROXY_CLIENT_SECRET_FILE
          value: /var/lib/keycloak/client-secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-cookie-secret
              key: secret
        readinessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /ping
            port: 8880

      volumes:
        - name: proxy-keycloak-creds
          csi:
            driver: identity.keycloak.org
            volumeAttributes:
              clientID: oauthproxy
