images:
  - name: profile-server
    newName: ghcr.io/thelab-ms/profile
    newTag: sha-edc5c9d

  - name: profile-visit-check-job
    newName: ghcr.io/thelab-ms/profile/visit-check-job
    newTag: sha-fa50574

  - name: profile-paypal-check-job
    newName: ghcr.io/thelab-ms/profile/paypal-check-job
    newTag: sha-fa50574

  - name: access-controller-controller
    newName: ghcr.io/thelab-ms/access-controller-controller
    newTag: main-28812bd

  - name: docuseal
    newName: docker.io/docuseal/docuseal
    digest: sha256:0e38d295c72f415ec647e8bfb52263703beb78ca725b2b67e52d0eb8e2bf1586

  - name: fobsvr
    newName: ghcr.io/thelab-ms/fobsvr
    newTag: "main-fb4208c"

  - name: frigate
    newName: ghcr.io/blakeblackshear/frigate
    newTag: "0.12.1"

  - name: homeassistant
    newName: ghcr.io/home-assistant/home-assistant
    newTag: "2023.11.3"

  - name: grafana
    newName: docker.io/grafana/grafana-oss
    newTag: "10.1.10"

  - name: keycloak
    newName: ghcr.io/thelab-ms/keycloak-extensions
    newTag: main-ce5b2d5

  - name: nvidia-device-plugin
    newName: nvcr.io/nvidia/k8s-device-plugin
    newTag: v0.14.3

  - name: prometheus
    newName: quay.io/prometheus/prometheus
    newTag: v2.52.0

  - name: prom-node-exporter
    newName: quay.io/prometheus/node-exporter
    newTag: v1.7.0

  - name: prom-mikrotik-exporter
    newName: ghcr.io/akpw/mktxp
    newTag: gha-5421251592

  - name: postgres
    newName: docker.io/postgres
    newTag: "15.3"

  - name: samba
    newName: ghcr.io/thelab-ms/samba
    newTag: sha-4e8f77b

  - name: wikijs
    newName: docker.io/requarks/wiki
    newTag: "2.5"

  - name: oauth2-proxy
    newName: quay.io/oauth2-proxy/oauth2-proxy
    newTag: v7.4.0

resources:
  - manifests/access-controller-controller.yaml
  - manifests/backups.yaml
  - manifests/cert-manager.ext.yaml
  - manifests/cert-manager.yaml
  - manifests/contour.ext.yaml
  - manifests/docuseal.yaml
  - manifests/fobsvr.yaml
  - manifests/frigate.yaml
  - manifests/gliderbot.yaml
  - manifests/grafana.yaml
  - manifests/homeassistant.yaml
  - manifests/keycloak.yaml
  - manifests/nvidia.ext.yaml
  - manifests/profile.yaml
  - manifests/prom.yaml
  - manifests/psql-keycloak.yaml
  - manifests/psql-reporting.yaml
  - manifests/psql-wikijs.yaml
  - manifests/redirects.yaml
  - manifests/samba.yaml
  - manifests/wikijs.yaml

patches:
  - path: patches/contour-ds.yaml
    target:
      group: apps
      version: v1
      kind: DaemonSet
      name: envoy
      namespace: projectcontour

  - path: patches/contour-svc.yaml
    target:
      version: v1
      kind: Service
      name: envoy
      namespace: projectcontour

  - path: patches/oauth-sidecar.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      annotationSelector: "oauth-sidecar=yes"

configMapGenerator:
  - name: prom-config
    files:
      - configs/prometheus.yml

  - name: frigate-config
    files:
      - configs/frigate.yml

  - name: grafana-config
    files:
      - configs/grafana.ini

  - name: backup-script
    files:
      - configs/backup.py
