resources:
  - manifests/access-controller-controller.yaml
  - manifests/docuseal.yaml
  - manifests/frigate.yaml
  - manifests/keycloak.yaml
  - manifests/nvidia.ext.yaml
  - manifests/profile-staging.yaml
  - manifests/profile.yaml
  - manifests/prom.yaml
  - manifests/wikijs.yaml

patches:
  - path: patches/oauth-sidecar.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      annotationSelector: "oauth-sidecar=yes"

configMapGenerator:
- name: prom-config
  files:
  - configs/prometheus.yml

- name: frigate-config
  files:
  - configs/frigate.yml
