apiVersion: apps/v1
kind: Deployment
metadata:
  name: access-controller-controller
  labels:
    app: access-controller-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: access-controller-controller
  template:
    metadata:
      labels:
        app: access-controller-controller
    spec:
      containers:
        - name: controller
          image: access-controller-controller
          volumeMounts:
            - name: keycloak-creds
              mountPath: /var/lib/keycloak
            - name: root-ca
              mountPath: /etc/ssl/certs
          env:
            - name: SWIPE_SCRAPE_INTERVAL
              value: "10s"
            - name: POSTGRES_HOST
              value: "psql-reporting.default.svc.cluster.local"
            - name: ACCESS_CONTROL_HOST
              value: 10.220.4.5:80
            - name: KEYCLOAK_URL
              value: http://keycloak.default.svc.cluster.local
            - name: AUTHORIZED_GROUP_ID
              value: 4eea9c17-f9b1-41eb-8f25-721ae04b66f6
            - name: CALLBACK_URL
              value: http://access-controller-controller.default.svc.cluster.local
            - name: WEBHOOK_ADDR
              value: :8080
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reporting-psql
                  key: password
      volumes:
        - name: keycloak-creds
          csi:
            driver: identity.keycloak.org
            volumeAttributes:
              clientID: access-controller
        - name: root-ca
          hostPath:
            path: /etc/ssl/certs/
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: access-controller-controller
spec:
  type: ClusterIP
  selector:
    app: access-controller-controller
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
