apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cto@thelab.ms
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        azureDNS:
          hostedZoneName: thelab.ms
          resourceGroupName: thelab-ms
          subscriptionID: 4eec622b-7eef-44e4-96e4-2b9fa2f21f07
          environment: AzurePublicCloud
          tenantID: f4ba79ec-fe30-424f-a96e-2de98f58f9b8
          clientID: 846d6a2c-6fa0-48f5-b810-f997cf8d8e50
          clientSecretSecretRef:
            name: azure-sp
            key: secret

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace: default
spec:
  secretName: wildcard-cert
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io
  commonName: "*.thelab.ms"
  dnsNames:
    - "*.thelab.ms"

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-wildcard
  namespace: default
spec:
  secretName: apps-wildcard-cert
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io
  commonName: "*.apps.thelab.ms"
  dnsNames:
    - "*.apps.thelab.ms"

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: internal-ca
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-ca
spec:
  isCA: true
  commonName: thelab-internal-ca
  secretName: internal-ca
  duration: 927100h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: internal-ca
    kind: Issuer
    group: cert-manager.io

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: internal
spec:
  ca:
    secretName: internal-ca
