apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate
  labels:
    app: frigate
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frigate
  template:
    metadata:
      labels:
        app: frigate
    spec:
      nodeName: supermicro2
      runtimeClassName: nvidia

      containers:
      - name: frigate
        image: ghcr.io/blakeblackshear/frigate:0.12.1
        volumeMounts:
          - name: cache
            mountPath: /tmp/cache
          - name: devshm
            mountPath: /dev/shm
          - name: media
            mountPath: /media/frigate
          - name: config
            mountPath: /config
        readinessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /api/
            port: 5000
        resources:
          limits:
            nvidia.com/gpu: "1"

      - name: oauth2proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
        securityContext:
          privileged: true
        volumeMounts:
          - name: proxy-keycloak-creds
            mountPath: /var/lib/keycloak
        env:
        - name: OAUTH2_PROXY_UPSTREAMS
          value: "http://127.0.0.1:5000"
        - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
          value: "true"
        - name: OAUTH2_PROXY_ALLOWED_GROUPS
          value: "thelab-leadership"
        - name: OAUTH2_PROXY_SCOPE
          value: "openid email profile"
        - name: OAUTH2_PROXY_HTTP_ADDRESS
          value: ":8888"
        - name: OAUTH2_PROXY_REDIRECT_URL
          value: "https://frigate.apps.thelab.ms/oauth2/callback"
        - name: OAUTH2_PROXY_EMAIL_DOMAINS
          value: "*"
        - name: OAUTH2_PROXY_CLIENT_ID
          value: "oauthproxy"
        - name: OAUTH2_PROXY_PROVIDER
          value: "keycloak-oidc"
        - name: OAUTH2_PROXY_PASS_USER_HEADERS
          value: "true"
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          value: "https://keycloak.apps.thelab.ms/realms/master"
        - name: OAUTH2_PROXY_CLIENT_SECRET_FILE
          value: /var/lib/keycloak/client-secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: frigate-oauth
              key: cookie-secret
        readinessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /ping
            port: 8888

      volumes:
        - name: proxy-keycloak-creds
          csi:
            driver: identity.keycloak.org
            volumeAttributes:
              clientID: oauthproxy
        - name: cache
          emptyDir:
            medium: Memory
            sizeLimit: 1G
        - name: devshm
          emptyDir:
            medium: Memory
            sizeLimit: 1G
        - name: media
          hostPath:
            path: /opt/frigate
        - name: config
          configMap:
            name: frigate-config

---

apiVersion: v1
kind: Service
metadata:
  name: frigate
spec:
  type: ClusterIP
  selector:
      app: frigate
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: frigate-unauthenticated
spec:
  type: ClusterIP
  selector:
      app: frigate
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate-config
data:
  config.yml: |
    mqtt:
      enabled: False

    record:
      enabled: True
      retain:
        days: 30
        mode: motion

    # detectors:
    #   cpu:
    #     type: cpu

    motion:
      frame_height: 25

    detect:
      enabled: False
      width: 640
      height: 360
      fps: 1

    cameras:
      Vent1:
        ffmpeg:
          hwaccel_args: preset-nvidia-h264
          inputs:
            - path: rtsp://admin:a1234567@10.200.0.11/live

      Vent2:
        ffmpeg:
          hwaccel_args: preset-nvidia-h264
          inputs:
            - path: rtsp://admin:a1234567@10.200.0.12/live
        motion:
          mask:
            - 363,48,307,200,230,154,276,0

      Atrium1:
        ffmpeg:
          hwaccel_args: preset-nvidia-h264
          inputs:
            - path: rtsp://10.200.0.13:554/Streaming/Channels/101

      # Atrium2:
      #   ffmpeg:
      #     hwaccel_args: preset-nvidia-h264
      #     inputs:
      #       - path: rtsp://10.200.0.14:554/Streaming/Channels/101
      #   motion:
      #     mask:
      #       - 368,0,362,42,321,40,325,0

      Woodshop1:
        ffmpeg:
          hwaccel_args: preset-nvidia-h264
          inputs:
            - path: rtsp://10.200.0.15:554/user=admin&password=&channel=1&stream=1.sdp?real_stream

      Woodshop2:
        ffmpeg:
          hwaccel_args: preset-nvidia-h264
          inputs:
            - path: rtsp://10.200.0.16:554/Streaming/Channels/101

      Classroom1:
        ffmpeg:
          hwaccel_args: preset-nvidia-h264
          inputs:
            - path: rtsp://10.200.0.17:554/Streaming/Channels/101
        motion:
          mask:
            - 109,163,105,28,28,33,39,182
            - 399,0,385,58,307,44,297,0
            - 340,360,548,360,545,140,345,182

      Classroom2:
        ffmpeg:
          hwaccel_args: preset-nvidia-h264
          inputs:
            - path: rtsp://admin:a1234567@10.200.0.18/live

      Cleanroom:
        ffmpeg:
          hwaccel_args: preset-nvidia-h264
          inputs:
            - path: rtsp://admin:a1234567@10.200.0.19/live

---

apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: frigate-oauth
spec:
  fields:
    - fieldName: "cookie-secret"
      encoding: "hex"
      length: "24"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frigate-exporter
  labels:
    app: frigate-exporter
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frigate-exporter
  template:
    metadata:
      labels:
        app: frigate-exporter
    spec:
      containers:
      - name: frigate-exporter
        image: ghcr.io/thelab-ms/frigate-exporter:main-8bf970e
        env:
        - name: POSTGRES_HOST
          value: "10.200.10.18"
        - name: FRIGATE_URL
          value: http://frigate-unauthenticated.default.svc.cluster.local
        - name: CAMERAS
          value: Vent1,Vent2,Atrium1,Atrium2,Woodshop1,Woodshop2,Classroom1,Classroom2,Cleanroom
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reporting-psql
              key: password
