apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
  annotations:
    oauth-sidecar: "yes"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: oauth2proxy
        env:
        - name: OAUTH2_PROXY_UPSTREAMS
          value: "http://127.0.0.1:3000"
        - name: OAUTH2_PROXY_REDIRECT_URL
          value: "https://grafana.apps.thelab.ms/oauth2/callback"
        - name: OAUTH2_PROXY_ALLOWED_GROUPS
          value: "thelab-leadership"

      - name: grafana
        image: grafana
        volumeMounts:
          - name: data
            mountPath: /var/lib/grafana
          - name: config
            mountPath: /etc/grafana
        readinessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /healthz
            port: 3000

      volumes:
        - name: data
          hostPath:
            path: /opt/grafana
        - name: config
          configMap:
            name: grafana-config

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: ClusterIP
  selector:
      app: grafana
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8880
