apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile
  labels:
    app: profile
  annotations:
    oauth-sidecar: "yes"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
      annotations:
        prometheus.io/port: "8081"
        prometheus.io/path: /metrics
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: svc
          image: profile-server
          volumeMounts:
            - name: keycloak-creds
              mountPath: /var/lib/keycloak
            - name: root-ca
              mountPath: /etc/ssl/certs
            - name: tmp
              mountPath: /tmp
          env:
            - name: KEYCLOAK_URL
              value: http://keycloak.default.svc.cluster.local
            - name: KEYCLOAK_MEMBERS_GROUP_ID
              value: 4eea9c17-f9b1-41eb-8f25-721ae04b66f6
            - name: SELF_URL
              value: https://profile.thelab.ms
            - name: PAYPAL_CLIENT_ID
              value: "AQVBErG_0lJAN5lhC_fSYUWvMjYpQrGxoCuO0jdAs7yiLVghlT0PpQflGIyL6DUAn5AFC_R9A0dHKkzu"
            - name: DOCUSEAL_URL
              value: https://docuseal.apps.thelab.ms
            - name: DOCUSEAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: docuseal
                  key: token
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-creds
                  key: secret
            - name: STRIPE_WEBHOOK_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-creds
                  key: webhook-key
            - name: PAYPAL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe-creds
                  key: paypal-secret
            - name: EVENT_PSQL_USERNAME
              value: postgres
            - name: EVENT_PSQL_ADDR
              value: "psql-reporting.default.svc.cluster.local"
            - name: EVENT_PSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reporting-psql
                  key: password
            - name: DISCORD_GUILD_ID
              value: "690314626289631294"
            - name: DISCORD_APP_ID
              value: "1121532987486523503"
            - name: DISCORD_EVENTS_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-token
                  key: eventsToken
            - name: DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-token
                  key: token
            - name: AGE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secrets-keys
                  key: AGE_PRIVATE_KEY
            - name: AGE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secrets-keys
                  key: AGE_PUBLIC_KEY
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 5
            httpGet:
              path: /health
              port: 8080

        - name: oauth2proxy
          env:
            - name: OAUTH2_PROXY_UPSTREAMS
              value: "http://127.0.0.1:8080"
            - name: OAUTH2_PROXY_SKIP_AUTH_ROUTES
              value: '.*(signup|assets|webhooks|events|prices|\/f\/).*'
            - name: OAUTH2_PROXY_REDIRECT_URL
              value: "https://profile.thelab.ms/oauth2/callback"

      volumes:
        - name: keycloak-creds
          csi:
            driver: identity.keycloak.org
            volumeAttributes:
              clientID: profile-app
        - name: root-ca
          hostPath:
            path: /etc/ssl/certs/
            type: Directory
        - name: tmp
          emptyDir:
            sizeLimit: 100Gi

---
apiVersion: v1
kind: Service
metadata:
  name: profile
spec:
  type: ClusterIP
  selector:
    app: profile
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8880

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: profile
spec:
  virtualhost:
    fqdn: profile.thelab.ms
    rateLimitPolicy:
      local:
        requests: 50
        unit: second
        burst: 50
    tls:
      secretName: wildcard-cert
  routes:
    - conditions:
        - prefix: /
      services:
        - name: profile
          port: 80

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: visit-check-job
spec:
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          nodeName: supermicro1
          restartPolicy: Never
          containers:
            - name: job
              imagePullPolicy: IfNotPresent
              image: profile-visit-check-job
              volumeMounts:
                - name: keycloak-creds
                  mountPath: /var/lib/keycloak
              env:
                - name: SELF_URL
                  value: https://profile.thelab.ms
                - name: KEYCLOAK_URL
                  value: http://keycloak.default.svc.cluster.local
                - name: KEYCLOAK_MEMBERS_GROUP_ID
                  value: 4eea9c17-f9b1-41eb-8f25-721ae04b66f6
                - name: EVENT_PSQL_USERNAME
                  value: postgres
                - name: EVENT_PSQL_ADDR
                  value: "psql-reporting.default.svc.cluster.local"
                - name: EVENT_PSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: reporting-psql
                      key: password
          volumes:
            - name: keycloak-creds
              csi:
                driver: identity.keycloak.org
                volumeAttributes:
                  clientID: profile-app

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: paypal-check-job
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          nodeName: supermicro1
          restartPolicy: Never
          containers:
            - name: job
              imagePullPolicy: IfNotPresent
              image: profile-paypal-check-job
              volumeMounts:
                - name: keycloak-creds
                  mountPath: /var/lib/keycloak
                - name: root-ca
                  mountPath: /etc/ssl/certs
              env:
                - name: SELF_URL
                  value: https://profile.thelab.ms
                - name: KEYCLOAK_URL
                  value: http://keycloak.default.svc.cluster.local
                - name: KEYCLOAK_MEMBERS_GROUP_ID
                  value: 4eea9c17-f9b1-41eb-8f25-721ae04b66f6
                - name: EVENT_PSQL_USERNAME
                  value: postgres
                - name: EVENT_PSQL_ADDR
                  value: "psql-reporting.default.svc.cluster.local"
                - name: EVENT_PSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: reporting-psql
                      key: password
                - name: PAYPAL_CLIENT_ID
                  value: "AQVBErG_0lJAN5lhC_fSYUWvMjYpQrGxoCuO0jdAs7yiLVghlT0PpQflGIyL6DUAn5AFC_R9A0dHKkzu"
                - name: PAYPAL_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: stripe-creds
                      key: paypal-secret
          volumes:
            - name: keycloak-creds
              csi:
                driver: identity.keycloak.org
                volumeAttributes:
                  clientID: profile-app
            - name: root-ca
              hostPath:
                path: /etc/ssl/certs/
                type: Directory
