apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-staging
  labels:
    app: profile-staging
  annotations:
    oauth-sidecar: "yes"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-staging
  template:
    metadata:
      labels:
        app: profile-staging
      annotations:
        prometheus.io/port: "8081"
        prometheus.io/path: /metrics
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: svc
          # Image is set in the profile app's deploy github action
          volumeMounts:
            - name: keycloak-creds
              mountPath: /var/lib/keycloak
            - name: root-ca
              mountPath: /etc/ssl/certs
          env:
            - name: KEYCLOAK_URL
              value: http://keycloak.default.svc.cluster.local
            - name: KEYCLOAK_MEMBERS_GROUP_ID
              value: 032aafbc-76ad-4b16-9e72-e814a5d341d7
            - name: SELF_URL
              value: https://profile-staging.thelab.ms
            - name: DOCUSEAL_URL
              value: https://docuseal.apps.thelab.ms
            - name: DOCUSEAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: docuseal
                  key: token
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-test-creds
                  key: secret
            - name: STRIPE_WEBHOOK_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-test-creds
                  key: webhook-key
            - name: AGE_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secrets-keys
                  key: AGE_PRIVATE_KEY
            - name: AGE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: web-secrets-keys
                  key: AGE_PUBLIC_KEY
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 5
            httpGet:
              path: /health
              port: 8080

        - name: oauth2proxy
          env:
            - name: OAUTH2_PROXY_UPSTREAMS
              value: "http://127.0.0.1:8080"
            - name: OAUTH2_PROXY_SKIP_AUTH_ROUTES
              value: '.*(signup|assets|webhooks|events|\/f\/).*'
            - name: OAUTH2_PROXY_REDIRECT_URL
              value: "https://profile-staging.thelab.ms/oauth2/callback"

      volumes:
        - name: keycloak-creds
          csi:
            driver: identity.keycloak.org
            volumeAttributes:
              clientID: profile-app

        - name: root-ca
          hostPath:
            path: /etc/ssl/certs/
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: profile-staging
spec:
  type: ClusterIP
  selector:
    app: profile-staging
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8880

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: profile-staging
spec:
  virtualhost:
    fqdn: profile-staging.thelab.ms
    rateLimitPolicy:
      local:
        requests: 50
        unit: second
        burst: 50
    tls:
      secretName: wildcard-cert
  routes:
    - conditions:
        - prefix: /
      services:
        - name: profile
          port: 80
