apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  labels:
    app: wikijs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
        - name: wikijs
          image: wikijs
          env:
            - name: HA_ACTIVE
              value: "true"
            - name: DB_TYPE
              value: "postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_NAME
              value: "postgres"
            - name: DB_HOST
              value: "psql-wikijs.default.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: wikijs
                  key: password
          readinessProbe:
            initialDelaySeconds: 2
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: wikijs
spec:
  type: ClusterIP
  selector:
    app: wikijs
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: wikijs
spec:
  virtualhost:
    fqdn: wiki.apps.thelab.ms
    rateLimitPolicy:
      local:
        requests: 50
        unit: second
        burst: 50
    tls:
      secretName: apps-wildcard-cert
  routes:
    - conditions:
        - prefix: /
      services:
        - name: wikijs
          port: 80
