mqtt:
  enabled: False

record:
  enabled: True
  retain:
    days: 30
    mode: motion

# detectors:
#   cpu:
#     type: cpu

motion:
  frame_height: 25

detect:
  enabled: False
  width: 640
  height: 360
  fps: 1

cameras:
  Vent1:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:a1234567@10.200.0.11/live

  Vent2:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:a1234567@10.200.0.12/live
    motion:
      mask:
        - 363,48,307,200,230,154,276,0

  Atrium1:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://10.200.0.13:554/Streaming/Channels/101

  Atrium2:
    ffmpeg:
      hwaccel_args: preset-nvidia-h265
      inputs:
        - path: rtsp://admin:thelab.ms@10.200.0.28:554/cam/realmonitor?channel=1&subtype=0

  Woodshop1:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://10.200.0.15:554/user=admin&password=&channel=1&stream=1.sdp?real_stream

  Woodshop2:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://10.200.0.16:554/Streaming/Channels/101

  Classroom1:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://10.200.0.17:554/Streaming/Channels/101
    motion:
      mask:
        - 109,163,105,28,28,33,39,182
        - 399,0,385,58,307,44,297,0
        - 340,360,548,360,545,140,345,182

  Classroom2:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:a1234567@10.200.0.18/live

  Cleanroom:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:a1234567@10.200.0.19/live