mqtt:
  enabled: False

record:
  enabled: True
  retain:
    days: 14
    mode: motion

# detectors:
#   cpu:
#     type: cpu

motion:
  frame_height: 25

detect:
  enabled: False
  width: 640
  height: 360
  fps: 1

cameras:
  Vent:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:thelab.ms@10.200.2.17:554/cam/realmonitor?channel=1&subtype=0

  Dungeon:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:thelab.ms@10.200.2.6:554/cam/realmonitor?channel=1&subtype=0

  Atrium:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:thelab.ms@10.200.2.13:554/cam/realmonitor?channel=1&subtype=0

  Woodshop:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://admin:thelab.ms@10.200.2.18:554/cam/realmonitor?channel=1&subtype=0

  Classroom:
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://10.200.2.16:554/Streaming/Channels/101

