network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s20f2:
      addresses:
        - 10.200.10.123/24
      dhcp4: no
      routes:
        - to: default
          via: 10.200.10.1
      nameservers:
          search: []
          addresses: [10.200.10.1]

  # we trunk the main members vlan here to enable home assistant mdns
  vlans:
    vlan.201:
      id: 201
      link: enp0s20f2
      routes:
        - to: 224.0.0.251/32
          via: 10.200.1.123
      addresses: [10.200.1.123/24]
