name: "kubectl apply"
on:
  push:
    branches:
      - "main"

jobs:
  apply:
    name: "kubectl apply"
    runs-on: ubuntu-latest
    container:
      image: docker.io/bitnami/kubectl:1.29.0
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - name: "Patch Image"
        run: |
          echo $KUBE_CONFIG | base64 -d > kc.yaml
          kubectl --kubeconfig kc.yaml apply --prune --all --kustomize .
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
          NEW_IMAGE: ${{ needs.push.outputs.tag }}
